security:
  encoders:
    # use your user class name here
    App\Entity\Internal\User:
      # Use native password encoder
      # This value auto-selects the best possible hashing algorithm
      # (i.e. Sodium when available).
      algorithm: auto
  providers:
    users:
      entity:
        # the class of the entity that represents users
        class: 'App\Entity\Internal\User'
        # the property to query by - e.g. username, email, etc
        property: 'username'
        # optional: if you're using multiple Doctrine entity
        # managers, this option defines which one to use
        # manager_name: 'customer'
  firewalls:
    main:
      pattern: ^/api
      http_basic:
        realm: "Secured Area"
      provider: users
  access_control:
    - { path: '^/api', roles: ROLE_USER }
    - { path: '^/admin/users', roles: ROLE_SUPER_ADMIN }
    - { path: '^/admin', roles: ROLE_ADMIN }